# # config/routes.yaml
# imports:
#     - { resource: routes/app_.yaml }

index:
    path: /
    controller: App\Controller\DefaultController::index

app_reservation:
    path: /reservation
    controller: App\Controller\ReservationController::index

dish_list:
    path: /dishes
    controller: App\Controller\DishController::list